# Generated by Django 3.2.7 on 2021-11-19 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fristapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('content', models.TextField()),
                ('image', models.ImageField(upload_to='fristapp/image')),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fristapp.website')),
            ],
        ),
    ]
