# Generated by Django 3.2.8 on 2021-11-13 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fristapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('ma_so', models.AutoField(primary_key=True, serialize=False)),
                ('ten', models.CharField(max_length=150, unique=True)),
            ],
        ),
    ]
