# Generated by Django 3.2.7 on 2021-12-03 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='password',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='fullname',
            field=models.TextField(max_length=250),
        ),
        migrations.AlterField(
            model_name='member',
            name='username',
            field=models.TextField(max_length=250, unique=True),
        ),
    ]
